#' @name gomoku_winner
#' @title Detects the name of the player who won the game of Gomoku
#' @description This function is not called directly. It is called within gomoku_victory() and is designed to be mapped to the rows, columns, and diagonals of the matrix generated by gomoku_play(). Using the rle() function it seeks out an instance in which either player has gotten 5 of their own tiles in a row, then stores this player's name (either "black" or "white") into a variable which is then returned.
#' @usage gomoku_winner(rle_output)
#' @param rle_output The list generated by the lapply(x, FUN =  rle) call within the gomoku_victory() function, where x is a vector containing the indices of the rows, columns or diagonals respectively.
#' @export
#' @return a list that indicate whether black or white is the winner based on the output of the rle function
#' @author Pin-Chun Chen and J Steven Raquel
 gomoku_winner <- function(rle_output) {
 if (5 %in% rle_output$lengths) {
     winner_list <- rle_output$values[which(rle_output$lengths == 5)]}
 else {winner_list <- NA}
 return(winner_list)
 }


